# Generated by Django 4.1.4 on 2022-12-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.IntegerField(blank=True, null=True)),
                ('tamanho', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('cor', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor do produto')),
                ('quantidade', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, max_length=250, null=True, upload_to='media/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('placa', models.CharField(max_length=50)),
                ('valor_servico', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('status_pag', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=100)),
                ('saldo', models.IntegerField()),
                ('servico', models.ManyToManyField(to='oficina.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor total')),
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oficina.servico')),
            ],
        ),
    ]
