# Generated by Django 4.1.4 on 2022-12-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='saldo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='servico',
            field=models.ManyToManyField(blank=True, null=True, to='oficina.servico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status_pag',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=100, null=True),
        ),
    ]
